import Head from "next/head";
import Layout from "../../components/Layout";
import { ProductItem } from "../../interface";
export const getStaticPaths = async () => {
    const res = await fetch("http://localhost:3000/api/products");
    const data = await res.json();
    const paths = data.message.map((a) => {
        return {
            params: {
                id: a._id.toString(),
            },
        };
    });
    return {
        paths,
        fallback: false,
    };
};

export const getStaticProps = async (context) => {
    const id = context.params.id;
    const res = await fetch("http://localhost:3000/api/detail/" + id);
    const data = await res.json();
    return {
        props: { product: data.message[0] },
    };
};

function detail({ product }: ProductItem) {
    return (
        <Layout>
            <Head>
                <title>{product.name}</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <div className="w-4/5 m-auto flex pt-5">
                    <div className="w-1/2 mr-3 relative">
                        <div className="sticky">
                            <img
                                src="https://cdn.tgdd.vn/Products/Images/42/251192/s16/iphone_14_pro_max_pdp_position-1_space_black_color-1-650x650.jpg"
                                alt=""
                            />
                        </div>
                        <div></div>
                    </div>
                    <div className="w-1/2 ml-2">
                        <h1>{product.name}</h1>
                        <h2>{product.price}</h2>
                        <div>
                            <p>Dung lượng</p>
                            <div>
                                <ul>
                                    {product.option.map((opt) => (
                                        <li key={opt}>{opt}</li>
                                    ))}
                                </ul>
                            </div>
                        </div>
                        <div>
                            <p>Màu</p>
                            <div>
                                <ul>
                                    {product.color.map((opt) => (
                                        <li>{opt}</li>
                                    ))}
                                </ul>
                            </div>
                        </div>
                        <div>
                            Khuyến mãi Giá và khuyến mãi dự kiến áp dụng đến
                            23:59 | 25/10
                            <ol>
                                <li>
                                    Thu cũ Đổi mới: Giảm đến 1.5 triệu (Tuỳ
                                    model máy cũ, không áp dụng kèm giảm giá qua
                                    cổng thanh toán) Xem chi tiết
                                </li>
                                <li>
                                    Giảm giá 35% iPad (Tuỳ model) khi mua kèm
                                    iPhone (Không kèm khuyến mãi khác của iPad)
                                    Xem chi tiết
                                </li>
                                <li>
                                    Giảm giá 35% iPad Pro M1 12.9" 2021 (tuỳ
                                    phiên bản) khi mua kèm iPhone (Không kèm
                                    khuyến mãi khác của iPad) Xem chi tiết
                                </li>
                                <li>
                                    Phụ kiện chính hãng Apple giảm 30% khi mua
                                    kèm iPhone Xem chi tiết
                                </li>
                                <li>
                                    {" "}
                                    Giảm 50% gói Bảo hiểm rơi vỡ 6 tháng (click
                                    xem chi tiết)
                                </li>
                                <li>
                                    Nhập mã SPPMWG giảm 10% tối đa 100.000đ khi
                                    thanh toán qua Ví ShopeePay (click xem chi
                                    tiết)
                                </li>
                                <li>
                                    {" "}
                                    Nhập mã TGDD giảm 4% tối đa 200.000đ cho đơn
                                    hàng từ 500.000đ trở lên khi thanh toán qua
                                    Ví Moca trên ứng dụng Grab (click xem chi
                                    tiết)
                                </li>
                            </ol>
                            <span>
                                (*) Giá hoặc khuyến mãi không áp dụng trả góp
                                lãi suất đặc biệt (0%, 0.5%, 1%)
                            </span>
                        </div>
                        <div>uu dai</div>
                        <div>mua</div>
                        <div>info</div>
                    </div>
                </div>
                <div></div>
            </div>
        </Layout>
    );
}

export default detail;
