import type { NextPage } from "next";
import Head from "next/head";
import Carousel from "../components/Carousel";
import Display from "../components/Display";
import Header from "../components/Header";
import Intro from "../components/Intro";
import TypeList from "../components/TypeList";
import { Products } from "../interface";

export async function getServerSideProps() {
    const result = await fetch(`http://localhost:3000/api/products`);
    const data = await result.json();
    return { props: { products: data.message } };
}

const Home: NextPage = ({ products }) => {
    const iphone = products.filter((e: Products) => {
        return e.type == "iphone";
    });
    const macbook = products.filter((e: Products) => {
        return e.type == "mac";
    });
    const ipad = products.filter((e: Products) => {
        return e.type == "ipad";
    });
    const watch = products.filter((e: Products) => {
        return e.type == "watch";
    });
    return (
        <div>
            <Head>
                <title>BotZone</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <Carousel />
            <Intro />
            <TypeList />
            <Display type="iPhone" data={iphone} />
            <Display type="Macbook" data={macbook} />
            <Display type="iPad" data={ipad} />
            <Display type="Watch" data={watch} />
        </div>
    );
};

export default Home;
