import Head from "next/head";
import Carousel from "../components/Carousel";
import Display from "../components/Display";
import Intro from "../components/Intro";
import Layout from "../components/Layout";
import TypeList from "../components/TypeList";
import { Products } from "../interface";
import React from "react";
import { home } from "../assets/imageLink/imageLink";

export async function getServerSideProps() {
  const result = await fetch("http://localhost:8080/" + `api/product`);
  const data = await result.json();
  return { props: { products: data.data } };
}

const Home = ({ products }: { products: Products[] }) => {
  const iphone = products.filter((e: Products) => {
    return e.type == "iphone";
  });
  const macbook = products.filter((e: Products) => {
    return e.type == "mac";
  });
  const ipad = products.filter((e: Products) => {
    return e.type == "ipad";
  });
  const watch = products.filter((e: Products) => {
    return e.type == "watch";
  });
  const accessory = products.filter((e: Products) => {
    return e.type == "accessory";
  });

  return (
    <Layout>
      <React.Fragment>
        <Head>
          <title>BotZone</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Carousel images={home} />
        <Intro />
        <TypeList />
        <Display type="iPhone" data={iphone} />
        <Display type="Macbook" data={macbook} />
        <Display type="iPad" data={ipad} />
        <Display type="Watch" data={watch} />
        <Display type="Accessory" data={accessory} />
      </React.Fragment>
    </Layout>
  );
};

export default Home;
