import type { NextPage } from "next";
import Head from "next/head";
import Carousel from "../components/Carousel";
import Display from "../components/Display";
import Header from "../components/Header";
import ImageSlider from "../components/ImageSlider";
import Intro from "../components/Intro";
import Layout from "../components/Layout";
import TypeList from "../components/TypeList";
import { Products } from "../interface";
import image from "../assets/images";

export async function getServerSideProps() {
  const result = await fetch(`http://localhost:8080/api/product`);
  const data = await result.json();
  return { props: { products: data.data } };
}

const Home: NextPage = ({ products }) => {
  const iphone = products.filter((e: Products) => {
    return e.type == "iphone";
  });
  const macbook = products.filter((e: Products) => {
    return e.type == "mac";
  });
  const ipad = products.filter((e: Products) => {
    return e.type == "ipad";
  });
  const watch = products.filter((e: Products) => {
    return e.type == "watch";
  });

  let images = Object.values(image);

  console.log(images);

  return (
    <Layout>
      <Head>
        <title>BotZone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Carousel images={images} />
      <Intro />
      <TypeList />
      <Display type="iPhone" data={iphone} />
      <Display type="Macbook" data={macbook} />
      <Display type="iPad" data={ipad} />
      {/* <Display type="Watch" data={watch} /> */}
    </Layout>
  );
};

export default Home;
