import { useStore, actions } from "../store";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import Link from "next/link";
import logo from "../assets/topzone";
import Head from "next/head";

function Register() {
  const [state, dispatch] = useStore();
  const [userName, setUserName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const router = useRouter();
  let data;
  // useEffect(() => {
  const register = async () => {
    const response = await fetch(
      "https://botzone.herokuapp.com/" + `api/register`,
      {
        method: "POST",
        // mode: "no-cors",
        headers: {
          "Content-Type": "application/x-www-form-urlencoded",
        },
        body: new URLSearchParams({
          name: userName,
          email: email,
          password: password,
        }),
      }
    );
    try {
      data = await response.json();
      if (data.code == 0) {
        setError(data.message);
      } else {
        setError(data.message);
      }
    } catch (e) {
      console.log(e);
    }
  };
  // }, []);

  let logoV = Object.values(logo);

  return (
    <>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full h-screen bg-[#3e3e3f] grid place-items-center">
        <div>
          <Link href="/">
            <div className="w-[30%] m-auto cursor-pointer">
              <img
                src={logoV[0].src}
                alt=""
                className="object-contain w-full"
              />
            </div>
          </Link>
          <div className="sm:w-[520px] md:w-[520px] bg-[#323232] m-auto rounded-xl p-5 shadow-2xl mt-4">
            <h2 className="font-medium text-4xl text-center">Register</h2>
            <form action="" className="space-y-4 mt-6">
              <div className="flex flex-col sm:flex-row">
                <div className="w-1/4 pb-2 sm:pb-0">Email:</div>
                <div className="flex-1 color-black">
                  <input
                    onChange={(e) => setEmail(e.target.value)}
                    type="email"
                    name="name"
                    className="w-full py-1 rounded-lg bg-[#f0f0f0] text-black pl-2"
                  />
                </div>
              </div>
              <div className="flex flex-col sm:flex-row">
                <div className="w-1/4 pb-2 sm:pb-0">Username:</div>
                <div className="flex-1 color-black">
                  <input
                    onChange={(e) => setUserName(e.target.value)}
                    type="text"
                    name="name"
                    className="w-full py-1 rounded-lg bg-[#f0f0f0] text-black pl-2"
                  />
                </div>
              </div>
              <div className="flex flex-col sm:flex-row">
                <div className="w-1/4 pb-2 sm:pb-0">Password:</div>
                <div className="flex-1 color-black">
                  <input
                    onChange={(e) => setPassword(e.target.value)}
                    type="password"
                    name="name"
                    className="w-full py-1 rounded-lg bg-[#f0f0f0] text-black pl-2"
                  />
                </div>
              </div>
              <div className="flex space-x-2 justify-center sm:justify-start">
                <div className="hidden sm:block">Đã có tài khoản? </div>
                <Link href="/login">
                  <div className="cursor-pointer ml-2 font-bold">Đăng nhập</div>
                </Link>
                <div>|</div>
                <Link href="/">
                  <div className="cursor-pointer ml-2 font-bold">
                    Trở về trang chủ
                  </div>
                </Link>
              </div>

              {error && <div className="text-red-600">{error}</div>}
              <div className="m-auto flex items-center justify-center py-2 rounded-2xl mt-3 bg-[#0071e3] cursor-pointer ">
                <div className="text-lg font-semibold " onClick={register}>
                  Register
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </>
  );
}

export default Register;
